import { useEffect, useState } from "react";
import axios from "axios";
import { Link, useParams } from "react-router-dom";
import { toast } from "react-toastify";

const inputClass = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2";
export default function EditEvent() {
  const { eventId } = useParams();
  const [form, setForm] = useState(null);
  const [banner, setBanner] = useState(null);
  useEffect(() => { axios.get(`${import.meta.env.VITE_BASE_URI}/club/getEvent`, { params: { eventId } }).then(({ data }) => { if (data.success) setForm(data.event); else toast.error(data.msg); }).catch(() => toast.error("Could not load event")); }, [eventId]);
  const save = async (event) => { event.preventDefault(); if (banner && (!['image/jpeg', 'image/png', 'image/webp'].includes(banner.type) || banner.size > 5 * 1024 * 1024)) return toast.error("Choose a JPG, PNG, or WebP image smaller than 5MB"); try { const payload = new FormData(); ["title", "shortDescription", "longDescription", "eligibility", "registerationDeadline", "maxParticipants", "registrationType", "minTeamSize", "maxTeamSize", "numberOfRounds"].forEach((key) => form[key] != null && payload.append(key, form[key])); if (banner) payload.append("eventBanner", banner); const { data } = await axios.patch(`${import.meta.env.VITE_BASE_URI}/club/events/${eventId}`, payload); if (!data.success) throw new Error(data.msg); setForm(data.event); setBanner(null); toast.success(data.msg); } catch (error) { toast.error(error.response?.data?.msg || error.message || "Could not save event"); } };
  if (!form) return <div className="p-8">Loading event editor…</div>;
  const set = (key, value) => setForm({ ...form, [key]: value });
  return <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><Link to={`/event/${eventId}`} className="text-sm font-semibold text-[#1a4b8e]">← Event overview</Link><h1 className="mt-4 text-3xl font-bold">Edit event</h1><form onSubmit={save} className="mt-6 space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><label className="block text-sm font-medium">Title<input className={inputClass} value={form.title || ""} onChange={(e) => set("title", e.target.value)} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Short description<textarea rows="3" className={inputClass} value={form.shortDescription || ""} onChange={(e) => set("shortDescription", e.target.value)} /></label><label className="text-sm font-medium">Eligibility<textarea rows="3" className={inputClass} value={form.eligibility || ""} onChange={(e) => set("eligibility", e.target.value)} /></label></div><label className="block text-sm font-medium">Full description<textarea rows="7" className={inputClass} value={form.longDescription || ""} onChange={(e) => set("longDescription", e.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Deadline<input type="date" className={inputClass} value={form.registerationDeadline || ""} onChange={(e) => set("registerationDeadline", e.target.value)} /></label><label className="text-sm font-medium">Registration type<select className={inputClass} value={form.registrationType || "team"} onChange={(e) => set("registrationType", e.target.value)}><option value="individual">Individual</option><option value="team">Team</option><option value="optional_team">Optional team</option></select></label><label className="text-sm font-medium">Min team<input type="number" min="1" className={inputClass} value={form.minTeamSize || 1} onChange={(e) => set("minTeamSize", e.target.value)} /></label><label className="text-sm font-medium">Max team<input type="number" min="1" className={inputClass} value={form.maxTeamSize || 1} onChange={(e) => set("maxTeamSize", e.target.value)} /></label></div><label className="block text-sm font-medium">Replace banner<input type="file" accept="image/jpeg,image/png,image/webp" className={inputClass} onChange={(e) => setBanner(e.target.files[0] || null)} /></label><button className="rounded-lg bg-[#1a4b8e] px-4 py-2 font-semibold text-white">Save event</button></form></div>;
}
