import { useEffect, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { toast } from "react-toastify";

const statuses = ["draft", "published", "closed", "archived", "cancelled"];
export default function Events() {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { axios.get(`${import.meta.env.VITE_BASE_URI}/club/getEvents`).then(({ data }) => data.success ? setEvents(data.events) : toast.error(data.msg)).catch(() => toast.error("Could not load events")).finally(() => setLoading(false)); }, []);
  const changeStatus = async (event, status) => { if (["cancelled", "archived"].includes(status) && !window.confirm(`${status} ${event.title}?`)) return; try { const { data } = await axios.patch(`${import.meta.env.VITE_BASE_URI}/club/events/${event._id}/status`, { status }); if (!data.success) throw new Error(data.msg); setEvents((items) => items.map((item) => item._id === event._id ? data.event : item)); toast.success(data.msg); } catch (error) { toast.error(error.response?.data?.msg || error.message); } };
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Recruitment events</h1><p className="mt-1 text-slate-600">Draft, publish, close, and review each recruitment pipeline.</p></div><Link to="/addEvent" className="rounded-lg bg-[#1a4b8e] px-4 py-2 font-semibold text-white">Create event</Link></div>{loading ? <p className="mt-8">Loading events…</p> : events.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center">No events yet.</div> : <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map((event) => <article key={event._id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{event.eventBanner && <img src={event.eventBanner} alt="" className="aspect-[16/6] w-full object-cover" />}<div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold">{event.title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold capitalize">{event.status}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{event.shortDescription}</p><p className="mt-3 text-sm text-slate-500">Deadline: {event.registerationDeadline || "Not set"}</p><label className="mt-4 block text-xs font-semibold uppercase text-slate-500">Lifecycle<select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm normal-case text-slate-900" value={event.status} onChange={(e) => changeStatus(event, e.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold"><Link className="text-[#1a4b8e]" to={`/event/${event._id}`}>Overview</Link><Link className="text-[#1a4b8e]" to={`/events/${event._id}/edit`}>Edit</Link><Link className="text-emerald-700" to={`/event-applications/${event._id}`}>Applications</Link></div></div></article>)}</div>}</div>;
}
