import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Link, useParams } from "react-router-dom";
import { toast } from "react-toastify";

const statuses = ["submitted", "in_progress", "waitlisted", "selected", "rejected", "withdrawn"];
const actionStatuses = statuses.filter((status) => status !== "withdrawn");
const inputClass = "rounded-lg border border-slate-300 px-3 py-2 text-sm";

export default function EventRegisteredStudents() {
  const { eventId } = useParams();
  const [event, setEvent] = useState(null);
  const [applications, setApplications] = useState([]);
  const [selected, setSelected] = useState([]);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => { try { const [eventResponse, applicationsResponse] = await Promise.all([axios.get(`${import.meta.env.VITE_BASE_URI}/club/getEvent`, { params: { eventId } }), axios.get(`${import.meta.env.VITE_BASE_URI}/club/getEventsRegisteredStudents`, { params: { eventId } })]); if (!eventResponse.data.success) throw new Error(eventResponse.data.msg); setEvent(eventResponse.data.event); setApplications(applicationsResponse.data.registeredStudents || []); } catch (error) { toast.error(error.response?.data?.msg || error.message || "Could not load applications"); } finally { setLoading(false); } }, [eventId]);
  useEffect(() => { load(); }, [load]);

  const visible = useMemo(() => applications.filter((application) => { const text = `${application.studentId?.name} ${application.studentId?.email} ${application.teamName || ""}`.toLowerCase(); return text.includes(search.toLowerCase()) && (filter === "all" || application.overallStatus === filter); }), [applications, search, filter]);

  const save = async (application, changes) => { try { const { data } = await axios.patch(`${import.meta.env.VITE_BASE_URI}/club/events/${eventId}/applications/${application._id}`, changes); if (!data.success) throw new Error(data.msg); setApplications((items) => items.map((item) => item._id === application._id ? { ...item, ...data.registration, studentId: item.studentId, membersAccepted: item.membersAccepted, eventId: item.eventId } : item)); toast.success(data.msg); } catch (error) { toast.error(error.response?.data?.msg || error.message); } };
  const bulkUpdate = async (status) => { if (!selected.length) return toast.info("Select at least one application"); if (["selected", "rejected"].includes(status) && !window.confirm(`Mark ${selected.length} application(s) as ${status}?`)) return; try { const { data } = await axios.post(`${import.meta.env.VITE_BASE_URI}/club/events/${eventId}/applications/bulk`, { registrationIds: selected, overallStatus: status }); if (!data.success) throw new Error(data.msg); setApplications((items) => items.map((item) => (data.updatedIds || []).includes(item._id) ? { ...item, overallStatus: status } : item)); setSelected([]); toast.success(data.msg); } catch (error) { toast.error(error.response?.data?.msg || error.message); } };
  const roundAction = async (application, action, roundNumber, roundDate) => { try { const payload = { eventId, studentId: application.studentId?._id, roundNumber: Number(roundNumber) }; if (roundDate) payload.roundDate = new Date(roundDate).toISOString(); const { data } = await axios.post(`${import.meta.env.VITE_BASE_URI}/club/${action}`, payload); if (!data.success) throw new Error(data.msg); toast.success(data.msg); await load(); } catch (error) { toast.error(error.response?.data?.msg || error.message); } };
  const exportCsv = async () => { try { const response = await axios.get(`${import.meta.env.VITE_BASE_URI}/club/events/${eventId}/applications/export`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${event?.title || "event"}-applications.csv`; link.click(); URL.revokeObjectURL(url); } catch { toast.error("Could not export applications"); } };

  if (loading) return <div className="p-8">Loading applications…</div>;
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><Link to={`/event/${eventId}`} className="text-sm font-semibold text-[#1a4b8e]">← Event overview</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{event?.title} applications</h1><p className="mt-1 text-slate-600">Review teams, record notes and scores, schedule rounds, and send decisions.</p></div><button onClick={exportCsv} className="rounded-lg border border-slate-300 px-4 py-2 font-semibold hover:bg-white">Export CSV</button></div>
    <div className="mt-6 flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-4"><input aria-label="Search applications" className={`${inputClass} min-w-64 flex-1`} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search captain, email, or team" /><select aria-label="Filter status" className={inputClass} value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</select><select aria-label="Bulk status" defaultValue="" className={inputClass} onChange={(e) => { if (e.target.value) bulkUpdate(e.target.value); e.target.value = ""; }}><option value="" disabled>Update selected…</option>{actionStatuses.map((status) => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</select></div>
    {visible.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No matching applications.</div> : <div className="mt-6 space-y-4">{visible.map((application) => <ApplicationCard key={application._id} application={application} checked={selected.includes(application._id)} onCheck={(checked) => setSelected((items) => checked ? [...items, application._id] : items.filter((id) => id !== application._id))} onSave={save} onRound={roundAction} />)}</div>}
  </div>;
}

function ApplicationCard({ application, checked, onCheck, onSave, onRound }) {
  const [notes, setNotes] = useState(application.reviewerNotes || "");
  const [score, setScore] = useState(application.score ?? "");
  const [round, setRound] = useState(Math.max(application.currentRound || 1, 1));
  const [roundDate, setRoundDate] = useState("");
  const members = [application.studentId, ...(application.membersAccepted || [])].filter(Boolean);
  return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start gap-3"><input type="checkbox" aria-label={`Select ${application.studentId?.name}`} checked={checked} onChange={(e) => onCheck(e.target.checked)} className="mt-1 h-4 w-4" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">{application.teamName || application.studentId?.name}</h2><p className="text-sm text-slate-500">Captain: {application.studentId?.name} · {application.studentId?.email}</p></div><select aria-label="Application status" disabled={application.overallStatus === "withdrawn"} className={inputClass} value={application.overallStatus} onChange={(e) => onSave(application, { overallStatus: e.target.value })}>{statuses.map((status) => <option key={status} value={status} disabled={status === "withdrawn" && application.overallStatus !== "withdrawn"}>{status.replace("_", " ")}</option>)}</select></div><p className="mt-3 text-sm text-slate-600"><strong>Team:</strong> {members.map((member) => member.name).join(", ")} ({members.length})</p><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_7rem_auto]"><textarea aria-label="Private reviewer notes" rows="2" className={inputClass} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Private reviewer notes" /><input aria-label="Score" type="number" min="0" max="100" className={inputClass} value={score} onChange={(e) => setScore(e.target.value)} placeholder="Score" /><button onClick={() => onSave(application, { reviewerNotes: notes, score: score === "" ? null : Number(score) })} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Save review</button></div>{application.numberOfRounds > 0 && application.overallStatus !== "withdrawn" && <div className="mt-4 flex flex-wrap items-end gap-3 rounded-lg bg-slate-50 p-3"><label className="text-xs font-semibold uppercase text-slate-500">Round<input type="number" min="1" max={application.numberOfRounds} value={round} onChange={(e) => setRound(e.target.value)} className={`${inputClass} mt-1 block w-20 bg-white`} /></label><label className="text-xs font-semibold uppercase text-slate-500">Schedule<input type="datetime-local" value={roundDate} onChange={(e) => setRoundDate(e.target.value)} className={`${inputClass} mt-1 block bg-white`} /></label><button onClick={() => onRound(application, "scheduleInterview", round, roundDate)} disabled={!roundDate} className="rounded-lg bg-[#1a4b8e] px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Schedule</button><button onClick={() => onRound(application, "selectStudentForRound", round)} className="rounded-lg border border-emerald-300 px-3 py-2 text-sm font-semibold text-emerald-700">Mark cleared</button></div>}</div></div></article>;
}
